"""
Fact classes for the Workout Expert System.

This module defines all fact types used by the expert engine.
Each fact represents a piece of knowledge that rules can match against.
"""

from experta import Fact, Field


class UserProfile(Fact):
    """Represents the user's fitness profile input.

    Fields:
        age (str): Age group — 'young', 'adult', or 'senior'.
        goal (str): Fitness goal — 'lose_weight', 'build_muscle',
                    'improve_endurance', or 'stay_healthy'.
        level (str): Fitness level — 'beginner', 'intermediate', or 'advanced'.
        available (str): Weekly availability — 'low', 'medium', or 'high'.
        condition (str): Health condition — 'healthy', 'joint_pain',
                         'heart_issue', or 'overweight'.
    """

    age = Field(str, mandatory=True)
    goal = Field(str, mandatory=True)
    level = Field(str, mandatory=True)
    available = Field(str, mandatory=True)
    condition = Field(str, mandatory=True)


class WorkoutRecommendation(Fact):
    """Represents a workout plan recommendation generated by the engine.

    Fields:
        workout_type (str): Type of workout (e.g., 'Cardio', 'Strength Training').
        intensity (str): Intensity level — 'low', 'moderate', or 'high'.
        frequency (str): Recommended sessions per week (e.g., '3-4 days/week').
        duration (str): Duration per session (e.g., '30-45 minutes').
        details (list): List of specific exercises or instructions.
    """

    workout_type = Field(str, mandatory=True)
    intensity = Field(str, mandatory=True)
    frequency = Field(str, mandatory=True)
    duration = Field(str, mandatory=True)
    details = Field(list, mandatory=True)


class Warning(Fact):
    """Represents a health or safety warning for the user.

    Warnings are triggered when the user has a medical condition
    that requires exercise modifications or precautions.

    Fields:
        message (str): The warning message to display.
    """

    message = Field(str, mandatory=True)
